### ISSUE TITLE
Add enterprise image properties

### ISSUE THREAD

**Issue by berendt** [osism/openstack-image-manager#136]
Like bring your own license or terms of use.

**Comment by garloff** [comment]
* EULA/Terms of Use (URL)
* Support status:
  - Support by CSP with OSV backing
  - Direct Support from OSV included
  - Supportable/Approved OSV image (but needs additional contract)
  - Not supported
* Licensing/Maintenance terms
  - License included in instance cost
  - BYOL (Bring your own license) required
  - Optional 
  - Not applicable (default?)

**Comment by garloff** [comment]
Let's also have a look what various CSPs do here ...

**Comment by berendt** [comment]
Will be fixed with #332.
