### ISSUE TITLE
Explain the available metadata in the README

### ISSUE THREAD

**Issue by tobfisch** [osism/openstack-image-manager#205]
I would like to know the reasoning behind the image_original_user property, introduced in this PR: https://github.com/osism/openstack-image-manager/pull/128. 
Is there a specific reason to name the property this way or was it just a design decision?

**Comment by berendt** [comment]
@garloff Do you remember where that came from? I mean from OVH or OTC?

**Comment by garloff** [comment]
This was indeed taken from OVH.

**Comment by berendt** [comment]
We should include a table in the README and explain in detail what each metadata means and where it comes from.

**Comment by garloff** [comment]
Anything particular that you think is missing from
https://github.com/SovereignCloudStack/Docs/blob/main/Design-Docs/Image-Properties-Spec.md
?

**Comment by berendt** [comment]
The content from there must be adapted accordingly here in the README.

**Comment by berendt** [comment]
Replaced by #336
