### ISSUE TITLE
Use os_hidden

### ISSUE THREAD

**Issue by berendt** [osism/openstack-image-manager#24]
http://specs.openstack.org/openstack/glance-specs/specs/rocky/approved/glance/operator-image-workflow.html

**Comment by horazont** [comment]
Link is dead, this is the new one: https://specs.openstack.org/openstack/glance-specs/specs/rocky/implemented/glance/operator-image-workflow.html

**Comment by tobfisch** [comment]
I've created a PR (https://github.com/SovereignCloudStack/openstack-image-manager/pull/175) which adds support to use os_hidden.
Please feel free to review and comment it or extent the PR.
