### ISSUE TITLE
Allow to specify multiple images with --name

### ISSUE THREAD

**Issue by sihensel** [osism/openstack-image-manager#278]
It is currently not possible to specify multiple image with the `--name` parameter.

Using `--name` multiple times results in only the last statement being processed, while `--name image1,image2` takes the whole input as a string literal.

By switching the `--name` parameter from `cfg.StrOpt` to `cfg.ListOpt` it becomes possible to specify multiple images via
`--name image1,image2`.

**Comment by berendt** [comment]
Simon will open a PR after merge of  #243
