### ISSUE TITLE
[feat] check for valid url targets

### ISSUE THREAD

**Issue by frosty-geek** [osism/openstack-image-manager#304]
I would like to be able to pre-flight check whether the URLs in the images.yml are still valid and can be downloaded or raise an error if they are unavailable.

Thus I would suggest that  [check.py](https://github.com/osism/openstack-image-manager/blob/0267b450749f394221bfdff3b3cb2a9b66f141ea/src/check.py#L32) should raise an error on r.status_code so one can act upon invalid URL definitions

comments?

ralf

**Comment by berendt** [comment]
Fixed with https://github.com/osism/openstack-image-manager/commit/e5dc12acb5b4d57ded11d685d0f92b78d39d62fd
