### ISSUE TITLE
Allow image manager to work without any S3. Maybe some daemon/pipeline style workflow.

### ISSUE THREAD

**Issue by tibeer** [osism/openstack-image-manager#319]
from @frosty-geek during lean operator coffee

**Comment by berendt** [comment]
This is already possible when not using the mirror functionality.

**Comment by tibeer** [comment]
Closing than.

**Comment by berendt** [comment]
I will explain this better in the documentation.

**Comment by berendt** [comment]
Hope it is better with #325
