### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by berendt** [osism/openstack-image-manager#336]
Check if the documentation is good enough to understand the idea of the tool and how to use it.

**Comment by fkr** [comment]
@maxwolfs and @berendt will go into discussion and use this a starting point for how this fits into the overall Information Architecture around SCS.

**Comment by berendt** [comment]
We had the call with Max, Ramona and Larissa today. Max is running a few more tests with a possible toolchain until the beginning of next week and we will then work through this repository as an example.

Furthermore, there will be a dedicated SIG Documentation where we will discuss these topics in the future. Max will clarify everything internally and set up the appointment.

**Comment by berendt** [comment]
Before we can start this task, the following items must be completed:

- [ ] appointment for SIG Documentation required
- [ ] proposal for tool chain by Max required
- [ ] proposal for document format by Max required
- [ ] proposal for overall document structure by Max required

**Comment by berendt** [comment]
- [ ] depends on https://github.com/osism/openstack-image-manager/issues/415

**Comment by berendt** [comment]
Max prepared an initial dosc repository (https://github.com/SovereignCloudStack/docs-page) in the SCS organisation. We now have to see how far we can adapt this so that the code and the associated documentation do not diverge. In our experience, code and documentation should be maintained in the same repository where possible. We will add this to the list of suggestions for the hackathon on Tuesday.

**Comment by berendt** [comment]
Before we start with the rewrite of this documentation we need to clarify the use of separate documentation repositories as well as the use of a Documentation Contributor Guide.

Depends on https://github.com/SovereignCloudStack/docs-page/issues/1.
Depends on https://github.com/SovereignCloudStack/docs-page/issues/2.

**Comment by garloff** [comment]
Publication is WIP (@maxwolfs).
Then purge old (.rst) stuff.

**Comment by fkr** [comment]
https://github.com/SovereignCloudStack/docs-page/pull/13/

**Comment by berendt** [comment]
That's done.
