### ISSUE TITLE
Images should be crawled by the Image Manager

### ISSUE THREAD

**Issue by fkr** [osism/openstack-image-manager#345]
- [x] https://github.com/osism/openstack-image-manager/issues/470
- [x] https://github.com/osism/openstack-image-manager/issues/459

**Comment by fkr** [comment]
Discussed in Team IaaS: the tool by @costelter should become a PR against the OpenStack Image Manager.
Work by @costelter: https://github.com/costelter/openstack-image-crawler

**Comment by frosty-geek** [comment]
FTR,
https://github.com/osism/openstack-image-manager/blob/main/.github/workflows/update-images.yml implements a very rudimentary update function already which will most likely be replaced by this.

**Comment by fkr** [comment]
@berendt and @costelter are in touch regarding the integration. @berendt is looking into ways on how to incorporate it midterm.

**Comment by garloff** [comment]
Merged contrib from @costelter into image-manager (with minimal adaptation) code base.
Integration (using it) will be done later, needs another discussion with Simon, Christian, ... (January).

**Comment by garloff** [comment]
Integration/activation of crawler into into-manager pending.

**Comment by berendt** [comment]
For the integration/migration of the code base in crawler/: #470

**Comment by berendt** [comment]
Crawler removed, can be closed here.
