### ISSUE TITLE
Discussion: rename `--check` and `--validate` commands

### ISSUE THREAD

**Issue by tibeer** [osism/openstack-image-manager#430]
Since the commands `--check` and `--validate` only affect SCS standards, we should name them `--check-scs` and `--validate-scs`

**Comment by sihensel** [comment]
IMO that depends on whether a user should be allowed to use their own validation schemes, i.e. provide a custom `schema.yaml` that reflects the image provision best practices for their own cloud.
If so, the CLI flags should remain the same, otherwise they can be renamed.

**Comment by berendt** [comment]
Replaced by #441.
