### ISSUE TITLE
Exception / error handling is reporting the wrong error

### ISSUE THREAD

**Issue by fkr** [osism/openstack-image-manager#657]
In this code piece: https://github.com/osism/openstack-image-manager/blame/4aa9fca869d3f25c1f4d54dab791c4eee606b599/openstack_image_manager/manage.py#L290-L336

there is an exception handling. If an exception is caught a specific error regarding the checksum url is gives as feedback to the user.
However aside from the specific case in which an exception is raised (https://github.com/osism/openstack-image-manager/blob/4aa9fca869d3f25c1f4d54dab791c4eee606b599/openstack_image_manager/manage.py#L314) exceptions can occur in other places, in those cases the printend error is misleading.

**Comment by lindenb1** [comment]
@fkr Take a look here, this should fix up your mentioned issues:

https://github.com/osism/openstack-image-manager/pull/658
