### ISSUE TITLE
Problem: Link in GitHub 'About' section is broken

### ISSUE THREAD

**Issue by julianpistorius** [osism/openstack-image-manager#747]
When I go to the GitHub repo: https://github.com/osism/openstack-image-manager

On the right-hand side there is the following text:

> **About**
> 
> Easily manage and keep up to date a large number of images on an OpenStack environment 

... and the link underneath is:

https://osism.github.io/docs/guides/operations-guide/openstack/image-manager/

... but should be:

https://osism.tech/docs/guides/operations-guide/openstack/day2-operations/image-manager

Note that the 'documentation' button in the README.md file goes to the right place:

> [![Documentation](https://img.shields.io/static/v1?label=&message=documentation&color=blue)](https://osism.github.io/docs/guides/operations-guide/openstack/day2-operations/image-manager)

**Comment by berendt** [comment]
@julianpistorius Thanks. We changed the domain a few days ago and have not yet corrected the URLs everywhere.
