### ISSUE TITLE
Feature request: Add base name to image metadata

### ISSUE THREAD

**Issue by mbuechse** [osism/openstack-image-manager#820]
By base name, I mean the name given in the image spec, without the appended version. It would be nice to have this as a property on the OpenStack Image as well, so it's easy to find all versions that belong together.

**Comment by gndrmnn** [comment]
Does the "base name" we are talking about here contain the distro specific version, or no version at all?
e.g. Is the base name of "Ubuntu 22.04" either "ubuntu" or something like "ubuntu-22.04"

**Comment by mbuechse** [comment]
I mean

> the name given in the image spec, without the appended version

in other words, I mean `image['name']` here:

https://github.com/osism/openstack-image-manager/blob/main/openstack_image_manager/main.py#L515
